[versions]
jdk     = '20'
junit   = '5.10.0'
assertj = '3.24.2'
mockito = '5.4.0'
okhttp  = '4.10.0'
apache  = '5.1.1'
jetty   = '11.0.13'
reactor = '1.1.2'

[libraries]
assertj = { module = 'org.assertj:assertj-core', version.ref = 'assertj' }
mockito = { module = 'org.mockito:mockito-core', version.ref = 'mockito' }
client-okhttp  = { module = 'com.squareup.okhttp3:okhttp', version.ref = 'okhttp' }
client-apache  = { module = 'org.apache.httpcomponents.client5:httpclient5', version.ref = 'apache' }
client-jetty   = { module = 'org.eclipse.jetty:jetty-client', version.ref = 'jetty' }
client-reactor = { module = 'io.projectreactor.netty:reactor-netty-http', version.ref = 'reactor' }

[bundles]
clients = ['client-okhttp', 'client-apache', 'client-jetty', 'client-reactor']
