name: Build Project
on: [ push, pull_request ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macOS-latest, ubuntu-latest ]
    steps:
        # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4.2.2
      - run: ./gradlew build
        # https://github.com/marketplace/actions/upload-a-build-artifact
      - uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: Gradle Reports (${{ matrix.os }})
          path: ./reports/build/
