name: Build Project
on: [ push, pull_request ]

jobs:
  build:
    name: Build using Java ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:   [ windows-latest, macOS-latest, ubuntu-latest ]
        java: [ '16', '17' ]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - run: ./gradlew build
      - uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: Gradle Reports (Java ${{ matrix.java }} on ${{ matrix.os }})
          path: ./build/reports/
          if-no-files-found: error