name: Build Project
on: [ push, pull_request ]

jobs:
  build:
    name: Build using Java ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:   [ windows-latest, macOS-latest, ubuntu-latest ]
        java: [ 11.0.10, 13.0.6, 15.0.2 ]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ matrix.java }}
      - run: ./gradlew build